# Generated by Django 5.2.10 on 2026-01-29 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', '-priority', '-created_at'], name='todos_user_id_f9e403_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', 'completed'], name='todos_user_id_e737ed_idx'),
        ),
    ]
